In [4]:
from numpy import *


In [5]:
arr = arange(1,11)

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [18]:
arr[arr % 3 == 0]

array([3, 6, 9])

In [19]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [21]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr.

SyntaxError: invalid syntax (1696555592.py, line 1)